current-places-on-map/.gitignore, current-places-on-map/Podfile, current-places-on-map/current-places-on-map.xcodeproj/project.pbxproj, current-places-on-map/current-places-on-map/AppDelegate.swift, current-places-on-map/current-places-on-map/Assets.xcassets/AppIcon.appiconset/Contents.json, current-places-on-map/current-places-on-map/Base.lproj/LaunchScreen.storyboard, current-places-on-map/current-places-on-map/Base.lproj/Main.storyboard, current-places-on-map/current-places-on-map/Info.plist, current-places-on-map/current-places-on-map/ViewController.swift
Adds new sample app for "places on a map" tutorial.
=> Adds new sample app

tutorials/places-address-form/places-address-form/Base.lproj/LaunchScreen.storyboard, tutorials/places-address-form/places-address-form/Base.lproj/Main.storyboard, tutorials/places-address-form/places-address-form/ViewController.swift
These are changes from Melby's review pass.
=> Integrated review changes (form constraints, minor code fix).

tutorials/map-with-marker/map-with-marker.xcodeproj/project.pbxproj, tutorials/map-with-marker/map-with-marker/AppDelegate.swift
Updating map-with-marker sample to use the
latest version of Swift. Project can now
be opened with versions of Xcode later
than 9.0
=> Updating to latest version of Swift

tutorials/current-place-on-map/current-place-on-map.xcodeproj/project.pbxproj, tutorials/current-place-on-map/current-place-on-map/AppDelegate.swift, tutorials/current-place-on-map/current-place-on-map/Base.lproj/Main.storyboard, tutorials/current-place-on-map/current-place-on-map/MapViewController.swift
Converting current-place-on-map demo from Swift 3 to Swift 5. Removing warnings caused by
update.
=> Updating demo current-place-on-map to latest version of Swift

tutorials/map-with-marker/map-with-marker.xcodeproj/project.pbxproj, tutorials/map-with-marker/map-with-marker/ViewController.h, tutorials/map-with-marker/map-with-marker/ViewController.m, tutorials/map-with-marker/map-with-marker/ViewController.swift, tutorials/map-with-marker/map-with-marker/map-with-marker-Bridging-Header.h
Fixing Tutorial so that it runs as well as adding an Objective-C sample.
=> fix: Update tutorial to modern usage.

tutorials/current-place-on-map/current-place-on-map/MapViewController.swift, tutorials/current-place-on-map/current-place-on-map/PlacesViewController.swift
Add region tags for 'Select Current Place' tutorial.
=> chore: Add region tags

tutorials/current-place-on-map/current-place-on-map/PlacesViewController.swift
Adding exclusion portion for region tag.
=> chore: Adding exclude portion for maps_ios_current_place_tableviewdelegate region tag.

.github/workflows/build.yml, MapsAndPlacesDemo/README.md
Adds to build new demo application
=> feat: Added to the build file to include the MapsAndPlaces demo application

MapsAndPlacesDemo/Podfile, snippets/PlacesSnippets/Podfile
Use stable 3.10.0 version of Google Maps and Google Places
=> chore: use Google Maps & Google Places 3.10.0 GA

.github/workflows/build.yml, snippets/MapsBetaSnippets/MapsBetaSnippets.xcodeproj/project.pbxproj, snippets/MapsBetaSnippets/MapsBetaSnippets/AppDelegate.swift, snippets/MapsBetaSnippets/MapsBetaSnippets/Assets.xcassets/AppIcon.appiconset/Contents.json, snippets/MapsBetaSnippets/MapsBetaSnippets/Assets.xcassets/Contents.json, snippets/MapsBetaSnippets/MapsBetaSnippets/Base.lproj/LaunchScreen.storyboard, snippets/MapsBetaSnippets/MapsBetaSnippets/Base.lproj/Main.storyboard, snippets/MapsBetaSnippets/MapsBetaSnippets/CloudBasedMapStylingViewController.h, snippets/MapsBetaSnippets/MapsBetaSnippets/CloudBasedMapStylingViewController.m, snippets/MapsBetaSnippets/MapsBetaSnippets/CustomPOIBehaviorViewController.h, snippets/MapsBetaSnippets/MapsBetaSnippets/CustomPOIBehaviorViewController.m, snippets/MapsBetaSnippets/MapsBetaSnippets/Info.plist, snippets/MapsBetaSnippets/MapsBetaSnippets/MapsBetaSnippets-Bridging-Header.h, snippets/MapsBetaSnippets/MapsBetaSnippets/PolylineCustomizationViewController.h, snippets/MapsBetaSnippets/MapsBetaSnippets/PolylineCustomizationViewController.m, snippets/MapsBetaSnippets/MapsBetaSnippets/SceneDelegate.swift, snippets/MapsBetaSnippets/MapsBetaSnippets/Swift/CloudBasedMapStylingViewController.swift, snippets/MapsBetaSnippets/MapsBetaSnippets/Swift/CustomPOIBehaviorViewController.swift, snippets/MapsBetaSnippets/MapsBetaSnippets/Swift/PolylineCustomizationViewController.swift, snippets/MapsBetaSnippets/MapsBetaSnippets/ViewController.swift, snippets/MapsBetaSnippets/Podfile
Add MapsBetaSnippets project for all Maps Beta related samples found in https://developers.google.com/maps/documentation/ios-sdk/overview
=> feat: Add MapsBetaSnippets project

.github/workflows/build.yml, snippets/MapsBetaSnippets/MapsBetaSnippets/MapsBetaSnippets-Bridging-Header.h, snippets/MapsSnippets/MapsSnippets.xcodeproj/project.pbxproj, snippets/MapsSnippets/MapsSnippets/AppDelegate.h, snippets/MapsSnippets/MapsSnippets/AppDelegate.m, snippets/MapsSnippets/MapsSnippets/Assets.xcassets/AppIcon.appiconset/Contents.json, snippets/MapsSnippets/MapsSnippets/Assets.xcassets/Contents.json, snippets/MapsSnippets/MapsSnippets/Base.lproj/LaunchScreen.storyboard, snippets/MapsSnippets/MapsSnippets/Base.lproj/Main.storyboard, snippets/MapsSnippets/MapsSnippets/Info.plist, snippets/MapsSnippets/MapsSnippets/MapWithMarkerViewController.h, snippets/MapsSnippets/MapsSnippets/MapWithMarkerViewController.m, snippets/MapsSnippets/MapsSnippets/SceneDelegate.h, snippets/MapsSnippets/MapsSnippets/SceneDelegate.m, snippets/MapsSnippets/MapsSnippets/Swift/MapWithMarkerViewController.swift, snippets/MapsSnippets/MapsSnippets/Swift/MapsSnippets-Bridging-Header.h, snippets/MapsSnippets/MapsSnippets/ViewController.h, snippets/MapsSnippets/MapsSnippets/ViewController.m, snippets/MapsSnippets/MapsSnippets/main.m, snippets/MapsSnippets/Podfile, tutorials/map-with-marker/map-with-marker/ViewController.m
=> chore: Adding MapsSnippets project.

tutorials/current-place-on-map/current-place-on-map.xcodeproj/project.pbxproj, tutorials/current-place-on-map/current-place-on-map/AppDelegate.swift, tutorials/current-place-on-map/current-place-on-map/MapViewController.h, tutorials/current-place-on-map/current-place-on-map/MapViewController.m, tutorials/current-place-on-map/current-place-on-map/MapViewController.swift, tutorials/current-place-on-map/current-place-on-map/PlacesViewController.h, tutorials/current-place-on-map/current-place-on-map/PlacesViewController.m, tutorials/current-place-on-map/current-place-on-map/PlacesViewController.swift, tutorials/current-place-on-map/current-place-on-map/current-place-on-map-Bridging-Header.h
=> chore: Add Obj-C sample for current-place-on-map

snippets/PlacesSnippets/PlacesSnippets.xcodeproj/project.pbxproj, snippets/PlacesSnippets/PlacesSnippets/AppDelegate.m, snippets/PlacesSnippets/PlacesSnippets/Base.lproj/Main.storyboard, snippets/PlacesSnippets/PlacesSnippets/PlaceAutocompleteViewController.h, snippets/PlacesSnippets/PlacesSnippets/PlaceAutocompleteViewController.m, snippets/PlacesSnippets/PlacesSnippets/Swift/PlaceAutocompleteViewController.swift
Add PlaceAutocompleteViewController.
=> chore: Add PlaceAutocompleteViewController.

snippets/MapsSnippets/Podfile, snippets/PlacesSnippets/Podfile, snippets/Podfile
**NOTE: We are not accepting external contributions at this time.**
If you find a bug or have a feature request related to these samples, please [file an issue](https://github.com/googlemaps/maps-sdk-for-ios-samples/issues).
If you find a bug or have a feature request related to one of the SDKs, you can file an issue on either the
[Google Maps SDK for iOS Issue Tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker).or the
[Places SDK for iOS Issue Tracker](https://issuetracker.google.com/savedsearches/5050150).
=> chore: Remove '=' sign from version

snippets/Podfile
Bump the version number to 4.1.0.
**NOTE: We are not accepting external contributions at this time.**
If you find a bug or have a feature request related to these samples, please [file an issue](https://github.com/googlemaps/maps-sdk-for-ios-samples/issues).
If you find a bug or have a feature request related to one of the SDKs, you can file an issue on either the
[Google Maps SDK for iOS Issue Tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker).or the
[Places SDK for iOS Issue Tracker](https://issuetracker.google.com/savedsearches/5050150).
=> chore: Update podfile for 4.1.0.

snippets/Cartfile
Increment the version number to 4.1.0 in cartfile.
=> chore: Update Cartfile for 4.1.0

.github/workflows/pod_try_sync.yml
**NOTE: We are not accepting external contributions at this time.**
If you find a bug or have a feature request related to these samples, please [file an issue](https://github.com/googlemaps/maps-sdk-for-ios-samples/issues).
If you find a bug or have a feature request related to one of the SDKs, you can file an issue on either the
[Google Maps SDK for iOS Issue Tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker).or the
[Places SDK for iOS Issue Tracker](https://issuetracker.google.com/savedsearches/5050150).
=> chore: Add workflow dispatch for pod_try_sync workflow

snippets/MapsBetaSnippets/MapsBetaSnippets/Swift/CustomPOIBehaviorViewController.swift
**NOTE: We are not accepting external contributions at this time.**
If you find a bug or have a feature request related to these samples, please [file an issue](https://github.com/googlemaps/maps-sdk-for-ios-samples/issues).
If you find a bug or have a feature request related to one of the SDKs, you can file an issue on either the
[Google Maps SDK for iOS Issue Tracker](https://developers.google.com/maps/documentation/ios-sdk/support#issue-tracker).or the
[Places SDK for iOS Issue Tracker](https://issuetracker.google.com/savedsearches/5050150).
=> chore: Update snippet enum usage.

.github/pull_request_template.md, README.md
=> chore: Remove note about not accepting PRs.

tutorials/current-place-on-map/Podfile, tutorials/map-with-marker/Podfile
=> chore: Add platform target to tutorials.

snippets/MapsSnippets/MapsSnippets/Markers.m, snippets/MapsSnippets/MapsSnippets/Swift/Markers.swift
=> chore(Snippet): Add new snippets to show/hide info window.

snippets/Cartfile, snippets/MapsBetaSnippets/Cartfile, snippets/MapsBetaSnippets/Podfile, snippets/MapsSnippets/Podfile, snippets/MapsUtilsSnippets/Podfile, snippets/PlacesSnippets/Podfile, snippets/Podfile
Change-Id: I7296e414248e858e04d77b361bc1eccee0e8eaf0
=> chore: Update snippets Podspec and Carthage to 6.2.0

snippets/MapsSnippets/MapsSnippets/CameraAndView.m, snippets/MapsSnippets/MapsSnippets/Swift/CameraAndView.swift
=> Add example to set camera target bounds.

snippets/Cartfile, snippets/XCFrameworkSnippets/Cartfile
=> fix: add xcframework settings to Cartfile.

snippets/MapsSnippets/Podfile, snippets/MapsUtilsSnippets/Podfile, snippets/PlacesSnippets/Podfile, snippets/Podfile
Bump version number for install instructions in documentation
=> chore: update snippets to v7.1.0

.github/workflows/pod_try_sync.yml
=> chore: fix pod try sync worfklow

snippets/MapsSnippets/Podfile, snippets/MapsUtilsSnippets/Podfile, snippets/PlacesSnippets/Podfile, snippets/Podfile
Bump version number for install instructions in documentation
=> chore: update snippets to v7.2.0

.github/workflows/pod_try_sync.yml
Hoping this does not re-open #157
=> chore: restore pod try sync to run on macos-latest

.github/workflows/pod_try_sync.yml
Including the GoogleNavigation demo in the repo.
---
---
=> Update pod_try_sync.yml to include GoogleNavigation

.github/workflows/build.yml
Add build steps for GoogleNavigation
=> Update build.yml to add GoogleNavigation

tutorials/current-place-on-map/current-place-on-map/MapViewController.m, tutorials/current-place-on-map/current-place-on-map/MapViewController.swift, tutorials/current-place-on-map/current-place-on-map/PlacesViewController.m, tutorials/current-place-on-map/current-place-on-map/PlacesViewController.swift
This unblocks doc changes to hide the apache license in our tutorials
=> Add macro tag for current place tutorial

snippets/MapsSnippets/Podfile
=> Update Podfile to Maps 9.1.0

snippets/Podfile
This change to be published when Maps 9.2.0 launches on 12/18/24.
---
---
=> Update Podfile to version 9.2.0

CODE_OF_CONDUCT.md, README.md
chore: update README per template
=> chore: update README per template
